pilkasite/pilkasite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('planner/', include('planner.urls')),
    path('', RedirectView.as_view(url='planner/', permanent=True)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

pilkasite/planner/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('players/', views.PlayerListView.as_view(), name='players'),
    path('player/<int:pk>', views.PlayerDetailView.as_view(), name='player-detail'),
    path('games/', views.GameListView.as_view(), name='games'),
    path('game/<int:pk>', views.GameDetailView.as_view(), name='game-detail'),
]

pilkasite/planner/models.py
from django.db import models
from django.urls import reverse

class Player(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    username = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    is_permanent = models.BooleanField()

    def __str__(self):
        return f'{self.name} {self.surname} aka {self.username}'

    def get_absolute_url(self):
        return reverse('player-detail', args=[str(self.id)])

class Game(models.Model):
    date = models.DateField()
    notes = models.TextField(max_length=2000)

    def __str__(self):
        return f'game at {self.date}'

    def get_absolute_url(self):
        return reverse('game-detail', args=[str(self.id)])


class Squad(models.Model):
    is_player_white = models.BooleanField()
    notes = models.TextField(max_length=1000, blank=True, default='')
    player = models.ForeignKey(Player, on_delete=models.SET_NULL, null=True)
    game = models.ForeignKey(Game, on_delete=models.SET_NULL, null=True)
    absent_player = models.OneToOneField(Player, on_delete=models.SET_NULL, null=True, blank=True, related_name='absent_player')
    substitution_order = models.SmallIntegerField(default=0)

    def __str__(self):
        kolor = 'czarnych'
        if self.is_player_white:
            kolor = 'białych'

        return f'{self.game.date} grał w {kolor} '


    def get_absolute_url(self):
        return reverse('squad-detail', args=[str(self.id)])

pilkasite/planner/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Player, Game, Squad


@login_required
def index(request):
    num_players = Player.objects.all().count()
    num_games = Game.objects.all().count()
    context = {
        'num_players': num_players,
        'num_games': num_games,
    }

    return render(request, 'index.html', context=context)


class PlayerListView(LoginRequiredMixin, generic.ListView):
    model = Player


class PlayerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Player


class GameListView(LoginRequiredMixin, generic.ListView):
    model = Game


class GameDetailView(LoginRequiredMixin, generic.DetailView):
    model = Game

pilkasite/planner/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Meczyki 2.0</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
	        <li><a href="{% url 'players' %}">Gracze</a></li>
          <li><a href="{% url 'games' %}">Mecze</a></li>
        </ul>
        <ul class="sidebar-nav">

          …
      
         {% if user.is_authenticated %}
           <li>User: {{ user.get_username }}</li>
           <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
         {% else %}
           <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
         {% endif %}
        </ul>
      
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

pilkasite/planner/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Meczyki 2.0 Home</h1>
  <p>Witaj na stronie meczyków stworzoną przez <em>Dzika</em>!</p>
  <h2>Dynamic content</h2>
  <p>W bazie mamy aktualnie rekordów:</p>
  <ul>
    <li><strong>Graczy:</strong> {{ num_players }}</li>
    <li><strong>Gier:</strong> {{ num_games }}</li>
  </ul>
{% endblock %}

pilkasite/planner/templates/planner/game_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Gra: {{ game.date }}</h1>
  <p><strong>Notatki:</strong> {{ game.notes }}</p>
  <p><b>Zapisanych graczy: {{game.squad_set.count}}</b></p>

  <div style="margin-left:20px;margin-top:20px">
    <h2>Zawodnicy</h2>
    <div>
      
    {% for squad in game.squad_set.all %}
      {% if squad.substitution_order > 0 %}
        <p>
          <p><a href="{{ squad.player.get_absolute_url }}">{{ squad.player.username }}</a>
            {{squad.substitution_order}} 
            (<a href="{{ squad.absent_player.get_absolute_url }}">{{ squad.absent_player.username }}</a>)
        </p>
      {% else %}
        <p><a href="{{ squad.player.get_absolute_url }}">{{ squad.player.username }}</a></p>
      {% endif %}
      
    {% endfor %}
    </div>

{% endblock %}

pilkasite/planner/templates/planner/game_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Lista gier</h1>
  {% if game_list %}
  <ul>
    {% for game in game_list %}
      <li>
	    <a href="{{ game.get_absolute_url }}">{{ game.date}}</a> ({{game.notes}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Nie ma żadnych gier w bazie.</p>
  {% endif %}
{% endblock %}

pilkasite/planner/templates/planner/player_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Player: {{ player.username }}</h1>

  <p><strong>Name:</strong> {{ player.name }}</p>
  <p><strong>Surname:</strong> {{ player.surname }}</p>
  <p><strong>Phone:</strong> {{ player.phone }}</p>
  <p><strong>email:</strong> {{ player.email }}</p>
  <p><strong>Permanent:</strong> {% if player.is_permanent %}YES{% else %}NO{% endif %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Mecze</h4>

    {% for squad in player.squad_set.all %}
      <p>{{ squad }}</p>
    {% endfor %}
  </div>


{% endblock %}

pilkasite/planner/templates/planner/player_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Lista graczy</h1>
  {% if player_list %}
  <h3>Stali gracze</h3>
  <ul>
    {% for player in player_list %}
      {% if player.is_permanent %}
        <li>
          <a href="{{ player.get_absolute_url }}">{{ player.username}}</a> ({{player.name}} {{player.surname}}) {% if player.is_permanent %}permi{% endif %}
        </li>
      {% endif %}
    {% endfor %}
  </ul>
  
  <h3>Zastępcy</h3>
  <ul>
    {% for player in player_list %}
      {% if not player.is_permanent %}
        <li>
          <a href="{{ player.get_absolute_url }}">{{ player.username}}</a> ({{player.name}} {{player.surname}}) {% if player.is_permanent %}permi{% endif %}
        </li>
      {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>Nie ma żadnych graczy w bazie.</p>
  {% endif %}
{% endblock %}